"""
SIMPLE: SIMulation-based Policy Learning and Evaluation

Copyright (c) 2025 Songlin Wei and Contributors
Licensed under the terms in LICENSE file.

------------------------------------------------------------------------------
Step 2 of the industrial-task asset pipeline (Plan A: real mesh collision).

Turns one warehouse-furniture USD (TableTrolley / GravityShelfBinOrganizer /
MobileShelvingCart) into a MuJoCo-ready STATIC asset:

    USD  ->  tessellated visual OBJ (meters)
         ->  VHACD convex decomposition  ->  N convex collision OBJs
         ->  MJCF snippet (visual geom + convex collision geoms), static body
         ->  standalone *_scene.xml (viewer-loadable)

Furniture is authored in centimeters (metersPerUnit = 0.01); we bake that factor
by default so the exported OBJ is in meters (MuJoCo: metersPerUnit = 1, up = Z).
Pass --units-scale to override, or --auto-units to read it from the USD.

USD is read via scripts/industrial/_usd_common.py (standalone pxr, no Kit boot).

Example:
    .venv/bin/python scripts/industrial/extract_furniture_mesh.py \
        --url  "https://.../TableTrolley_B/TableTrolley_B02_01.usd" \
        --name TableTrolley_B02_01 --out-dir data/assets/industrial --max-hulls 32
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _usd_common import decompose, download, stage_meters_per_unit, usd_to_trimesh  # noqa: E402


def write_mjcf_snippet(name: str, n_hulls: int, out_path: str) -> None:
    """Emit an MJCF include: static furniture body, visual mesh + convex collision."""
    coll = "\n".join(
        f'    <geom type="mesh" mesh="{name}_col_{i}" class="industrial_col"/>'
        for i in range(n_hulls)
    )
    asset_meshes = [f'  <mesh name="{name}_vis" file="visuals/{name}.obj"/>']
    asset_meshes += [
        f'  <mesh name="{name}_col_{i}" file="collision/{name}_col_{i}.obj"/>'
        for i in range(n_hulls)
    ]
    meshes = "\n".join(asset_meshes)
    xml = f"""<mujocoinclude>
  <!-- Auto-generated by scripts/industrial/extract_furniture_mesh.py -->
  <!-- Static warehouse furniture: full visual mesh + {n_hulls} convex collision hulls (VHACD). -->
  <default>
    <default class="industrial_col">
      <geom group="3" condim="3" friction="1 0.02 0.001"/>
    </default>
    <default class="industrial_vis">
      <geom group="1" type="mesh" contype="0" conaffinity="0"/>
    </default>
  </default>
  <asset>
{meshes}
  </asset>
  <!-- Place this body at the pose from ih_layout.json (yaw about Z). -->
  <worldbody>
    <body name="{name}" pos="0 0 0" euler="0 0 0">
{coll}
      <geom type="mesh" mesh="{name}_vis" class="industrial_vis"/>
    </body>
  </worldbody>
</mujocoinclude>
"""
    with open(out_path, "w") as f:
        f.write(xml)


def write_attach_mjcf(name: str, n_hulls: int, out_path: str) -> None:
    """Full-model MJCF for MjSpec.from_file + attach (the engine's articulated path).

    A standalone <mujoco> model (not a <mujocoinclude> fragment) holding just the
    static furniture body (visual mesh + convex collision, no joint -> welded when
    attached at a frame). This is what the task feeds as the furniture's mjcf_path.
    """
    asset_meshes = [f'  <mesh name="{name}_vis" file="visuals/{name}.obj"/>']
    asset_meshes += [
        f'  <mesh name="{name}_col_{i}" file="collision/{name}_col_{i}.obj"/>'
        for i in range(n_hulls)
    ]
    meshes = "\n".join(asset_meshes)
    coll = "\n".join(
        f'      <geom type="mesh" mesh="{name}_col_{i}" group="3" condim="3" friction="1 0.02 0.001"/>'
        for i in range(n_hulls)
    )
    xml = f"""<mujoco model="{name}">
  <compiler meshdir="." angle="radian"/>
  <asset>
{meshes}
  </asset>
  <worldbody>
    <body name="{name}">
{coll}
      <geom type="mesh" mesh="{name}_vis" group="1" contype="0" conaffinity="0"/>
    </body>
  </worldbody>
</mujoco>
"""
    with open(out_path, "w") as f:
        f.write(xml)


def write_scene(name: str, out_path: str) -> None:
    """Standalone viewer-loadable scene wrapping the <mujocoinclude> fragment."""
    with open(out_path, "w") as f:
        f.write(
            f'<mujoco model="{name}_scene">\n'
            f'  <compiler meshdir="." angle="radian"/>\n'
            f'  <option timestep="0.005" gravity="0 0 -9.81"/>\n'
            f'  <include file="{name}.mjcf.xml"/>\n'
            f"  <worldbody>\n"
            f'    <light pos="0 0 4" dir="0 0 -1"/>\n'
            f'    <geom name="floor" type="plane" size="5 5 0.1" rgba="0.4 0.4 0.4 1"/>\n'
            f"  </worldbody>\n"
            f"</mujoco>\n"
        )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--url", help="Source USD URL (S3). Omit if --usd is local.")
    ap.add_argument("--usd", help="Local USD path (overrides download).")
    ap.add_argument("--name", required=True, help="Asset name / folder.")
    ap.add_argument("--out-dir", default="data/assets/industrial")
    ap.add_argument("--units-scale", type=float, default=0.01, help="cm->m default.")
    ap.add_argument("--auto-units", action="store_true", help="Read scale from USD metersPerUnit.")
    ap.add_argument("--max-hulls", type=int, default=32)
    args = ap.parse_args()

    base = os.path.join(args.out_dir, args.name)
    vis_dir = os.path.join(base, "visuals")
    col_dir = os.path.join(base, "collision")
    os.makedirs(vis_dir, exist_ok=True)
    os.makedirs(col_dir, exist_ok=True)

    usd_path = args.usd
    if usd_path is None:
        assert args.url, "provide --usd or --url"
        usd_path = download(args.url, os.path.join(base, f"{args.name}.usd"))

    units = stage_meters_per_unit(usd_path) if args.auto_units else args.units_scale
    print(f"[mesh] tessellating {usd_path} (units_scale={units})")
    mesh = usd_to_trimesh(usd_path, units)
    ext = mesh.bounds[1] - mesh.bounds[0]
    print(
        f"[mesh] {len(mesh.vertices)} verts, {len(mesh.faces)} faces, "
        f"size(m)=({ext[0]:.3f},{ext[1]:.3f},{ext[2]:.3f}), watertight={mesh.is_watertight}"
    )

    vis_obj = os.path.join(vis_dir, f"{args.name}.obj")
    mesh.export(vis_obj)
    print(f"[vis] -> {vis_obj}")

    print(f"[vhacd] decomposing (max_hulls={args.max_hulls}) ...")
    hulls = decompose(mesh, args.max_hulls)
    print(f"[vhacd] {len(hulls)} convex hulls")
    for i, h in enumerate(hulls):
        h.export(os.path.join(col_dir, f"{args.name}_col_{i}.obj"))
    print(f"[col] -> {col_dir}/{args.name}_col_*.obj")

    mjcf = os.path.join(base, f"{args.name}.mjcf.xml")
    write_mjcf_snippet(args.name, len(hulls), mjcf)
    print(f"[mjcf] -> {mjcf}")

    attach = os.path.join(base, f"{args.name}_attach.xml")
    write_attach_mjcf(args.name, len(hulls), attach)
    print(f"[attach] -> {attach}  (MjSpec.from_file + attach; task furniture mjcf_path)")

    scene = os.path.join(base, f"{args.name}_scene.xml")
    write_scene(args.name, scene)
    print(f"[scene] -> {scene}  (open with: python -m mujoco.viewer --mjcf={scene})")
    print("[done]")


if __name__ == "__main__":
    main()
