"""
SIMPLE: SIMulation-based Policy Learning and Evaluation

Copyright (c) 2025 Songlin Wei and Contributors
Licensed under the terms in LICENSE file.

Validate curobo motion planning for Miss's ViperX arm, with live MuJoCo visualization. Mirrors
scripts/test_widowx_ai_curobo_ik.py's approach (drive the real robot through Cartesian waypoints
solved by curobo IK, measure settling error) but standalone -- no gym env exists for Miss yet
(see docs/source/miss/miss_integration.md, "Known limitations") -- and deliberately keeps the
gimbal OUT of curobo entirely: the gimbal is not part of the arm's kinematic chain, is not in
curobo/miss.yml's cspace, and is driven here by plain position-actuator commands
(GIMBAL_PRESETS), the same way scripts/test_miss_gimbal_arm.py does it.

HOW CUROBO CONTROLS MISS'S ARM, CONCRETELY
---------------------------------------------
Same mechanism as WidowX AI's script (see that file's own docstring for the fuller explanation):
`Miss.fk()`/`Miss.ik()` (via `CuRoboMixin`, `src/simple/robots/mixin.py`) wrap curobo's
`CudaRobotModel`/`IKSolver`, built from `data/robots/miss/curobo/miss.yml`
(`cspace.joint_names` = the 7 arm+gripper joints, `ee_link = vx300s/ee_gripper_link`). IK
solutions are applied as `data.actuator(jname).ctrl = value` for the 6 arm joints; the gripper
and gimbal are driven separately (never through `target_qpos`), matching the convention every
other robot in this codebase uses (see e.g. `WidowXAI.apply_action`'s own comment on this).

WAYPOINT PROVENANCE
--------------------
Unlike WidowX AI's hand-picked-then-verified waypoints, these were generated by taking `Miss.fk()`
at a handful of representative joint configurations (home, upright, and four reach poses spanning
the arm's shoulder/elbow/wrist range) and using the resulting Cartesian poses as IK targets --
i.e. each one is trivially guaranteed IK-reachable by construction (curobo just needs to recover
the joint config FK was computed from, not necessarily the exact same one thanks to redundancy,
but *a* valid one). This validates the FK/IK/self-collision/actuator round trip end-to-end; it
does not validate reachability of arbitrary/adversarial poses.

USAGE
-----
Watch it move in the MuJoCo viewer (needs a display):
    .venv/bin/python scripts/test_miss_curobo_ik.py --no-headless

Fast, no GUI (settling-error report only):
    .venv/bin/python scripts/test_miss_curobo_ik.py --headless

Reproduce with self-collision checking off (curobo's default is on and already confirmed working
for Miss, unlike WidowX AI -- this flag exists for comparison/debugging, not because it's needed):
    .venv/bin/python scripts/test_miss_curobo_ik.py --no-self-collision

Exit code is 0 iff every waypoint both (a) found an IK solution and (b) settled within
--pos-tol of the commanded position.
"""

from __future__ import annotations

import sys
import time
from typing import Annotated

import mujoco
import numpy as np
import typer

from simple.robots.miss import GIMBAL_PRESETS, GRIPPER_PRESETS, Miss

# Cartesian (position[m], quaternion[wxyz]) waypoints -- see module docstring "WAYPOINT
# PROVENANCE" for how these were generated (Miss.fk() at representative joint configs, not
# hand-guessed). gimbal_preset is applied directly via actuator ctrl, entirely outside curobo.
WAYPOINTS: list[dict] = [
    dict(name="home", p=[0.4770, 0.0, 1.3205], q=[0.0, 0.7071, 0.0, 0.7071], gripper="open_eef", gimbal_preset="stow"),
    dict(name="reach_low", p=[0.3547, 0.0, 1.4582], q=[0.0, 0.8048, 0.0, 0.5935], gripper="close_eef", gimbal_preset="look_down"),
    dict(name="reach_fwd", p=[0.5899, 0.0, 1.3698], q=[0.0, 0.7071, 0.0, 0.7071], gripper="open_eef", gimbal_preset="look_down"),
    dict(name="reach_side", p=[0.7214, -0.2882, 1.2052], q=[0.2463, -0.7963, 0.1633, -0.5279], gripper="close_eef", gimbal_preset="look_down_more"),
    dict(name="reach_side2", p=[0.7214, 0.2882, 1.2052], q=[0.2463, 0.7963, 0.1633, 0.5279], gripper="open_eef", gimbal_preset="stow"),
    dict(name="upright", p=[0.9540, 0.0, 0.8435], q=[0.0, -1.0, 0.0, 0.0], gripper="close_eef", gimbal_preset="stow"),
]


def main(
    headless: Annotated[
        bool, typer.Option(help="False opens the MuJoCo viewer so you can watch it move.")
    ] = True,
    settle_steps: Annotated[
        int, typer.Option(help="mj_step() calls per waypoint, letting actuators converge.")
    ] = 1200,
    pos_tol: Annotated[
        float,
        typer.Option(
            help=(
                "Max FK-measured position error (m) counted as a pass. These are P-only "
                "position actuators (no integral term) -- a residual few cm of steady-state "
                "droop against gravity/friction is expected, not a bug (same finding as "
                "scripts/test_miss_gimbal_arm.py's joint-space settling); 0.04 m is realistic "
                "for this hardware, not a tuned bound."
            )
        ),
    ] = 0.04,
    self_collision: Annotated[
        bool,
        typer.Option(
            "--self-collision/--no-self-collision",
            help="curobo self-collision checking for the arm IK solver (on by default -- already confirmed working for Miss, unlike WidowX AI).",
        ),
    ] = True,
    real_time: Annotated[bool, typer.Option(help="Pace playback in --no-headless mode.")] = True,
):
    """Drive Miss's arm through Cartesian waypoints via curobo IK; move the gimbal directly (no curobo)."""
    from simple.utils import resolve_data_path

    robot = Miss()
    # robot.mjcf_path is a relative data path; resolve it the same way CuRoboMixin resolves
    # robot_cfg, so this script works regardless of where data/ is rooted.
    model = mujoco.MjModel.from_xml_path(resolve_data_path(robot.mjcf_path, auto_download=True))
    data = mujoco.MjData(model)
    robot.setup_control(data, model)

    # Start at Home/Home/stow -- the class-level default, confirmed collision-free.
    for jname, val in robot.init_joint_states.items():
        data.joint(jname).qpos[0] = val
        data.actuator(jname).ctrl = val
    for jname, val in GIMBAL_PRESETS["stow"].items():
        data.joint(jname).qpos[0] = val
        data.actuator(jname).ctrl = val
    mujoco.mj_forward(model, data)

    viewer_ctx = None
    if not headless:
        from mujoco import viewer as mj_viewer

        viewer_ctx = mj_viewer.launch_passive(model, data)

    n_pass = 0
    try:
        for i, wp in enumerate(WAYPOINTS):
            target_p = np.asarray(wp["p"], dtype=np.float32)
            target_q = np.asarray(wp["q"], dtype=np.float32)
            current_qpos = np.asarray([data.joint(j).qpos[0] for j in robot.kin_model.joint_names], dtype=np.float32)

            try:
                if self_collision:
                    ik_qpos = robot.ik(target_p, target_q, current_joint=current_qpos)
                else:
                    import torch
                    from curobo.types.base import TensorDeviceType
                    from curobo.types.math import Pose
                    from curobo.wrap.reacher.ik_solver import IKSolver

                    tensor_args = TensorDeviceType()
                    ik_solver = IKSolver(
                        IKSolver.load_from_robot_config(
                            robot.robot_cfg, regularization=True, tensor_args=tensor_args,
                            self_collision_check=False, self_collision_opt=False,
                        )
                    )
                    goal = Pose(
                        tensor_args.to_device(torch.as_tensor(target_p, dtype=torch.float32)),
                        tensor_args.to_device(torch.as_tensor(target_q, dtype=torch.float32)),
                    )
                    retract_cfg = torch.as_tensor(current_qpos, dtype=torch.float32).cuda()
                    seed_cfg = retract_cfg.unsqueeze(0).repeat(1, 1).cuda().unsqueeze(0)
                    result = ik_solver.solve_single(goal, retract_cfg, seed_cfg)
                    if not bool(result.success[0, 0]):
                        raise RuntimeError("IK failed!")
                    ik_qpos = result.solution[0, 0].cpu().numpy()
            except RuntimeError as e:
                print(f"[{i}] {wp['name']:12s} IK FAILED: {e}")
                continue

            # Gripper is driven separately (open_eef/close_eef), never through target_qpos --
            # same convention as every other robot's apply_action in this codebase.
            target_qpos = dict(zip(robot.kin_model.joint_names, ik_qpos.tolist()))
            target_qpos.pop("left_finger", None)
            for jname, jval in target_qpos.items():
                data.actuator(jname).ctrl = jval
            gripper_ctrl = GRIPPER_PRESETS["released"] if wp["gripper"] == "open_eef" else GRIPPER_PRESETS["grasping"]
            data.actuator("left_finger").ctrl = gripper_ctrl

            # Gimbal: plain position-actuator command, entirely outside curobo/IK.
            for jname, jval in GIMBAL_PRESETS[wp["gimbal_preset"]].items():
                data.actuator(jname).ctrl = jval

            dt = model.opt.timestep
            for _ in range(settle_steps):
                step_start = time.monotonic()
                mujoco.mj_step(model, data)
                if viewer_ctx is not None:
                    viewer_ctx.sync()
                    if real_time:
                        sleep_for = dt - (time.monotonic() - step_start)
                        if sleep_for > 0:
                            time.sleep(sleep_for)

            achieved_qpos = np.asarray([data.joint(j).qpos[0] for j in robot.kin_model.joint_names], dtype=np.float32)
            achieved_p, achieved_q = robot.fk(achieved_qpos.tolist())
            pos_err = float(np.linalg.norm(achieved_p - target_p))
            ok = pos_err < pos_tol
            n_pass += int(ok)
            status = "OK" if ok else "FAIL (did not settle within tol)"
            print(
                f"[{i}] {wp['name']:12s} target={np.round(target_p, 3)} "
                f"achieved={np.round(achieved_p, 3)} err={pos_err:.4f}m "
                f"gripper={wp['gripper']} gimbal={wp['gimbal_preset']:15s} -> {status}"
            )
    finally:
        if viewer_ctx is not None:
            viewer_ctx.close()

    print(f"\n{n_pass}/{len(WAYPOINTS)} waypoints converged within {pos_tol} m.")
    sys.exit(0 if n_pass == len(WAYPOINTS) else 1)


if __name__ == "__main__":
    typer.run(main)
